### ISSUE TITLE
Documentation on using composer with private repositories

### ISSUE THREAD

**Issue by htollefsen** [shivammathur/setup-php#107]
**Is your feature request related to a problem? Please describe.**
It would be nice to see an example where private composer packages are used

**Describe the solution you'd like**
Some way to pass GITHUB_TOKEN without creating a COMPOSER_AUTH secret for every repository where an action is used

**Describe alternatives you've considered**
Ive tried to use `composer config` before doing `composer install`:
```
run: |
    composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
    composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
```
Ive also tried to concatinate COMPOSER_AUTH and pass it in env:
```
env:
    COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GITHUB_TOKEN }}" }}'
```
**Additional context**
n/a

**Comment by mathieu-bour** [comment]
The `GITHUB_TOKEN` secret won't work in your context because is it **scoped to the current repository**. I had the same problem on my project and I had to create a personal access token.
To generate such a personal access token, simply go to [https://github.com/settings/tokens] and make a token with the `repo` scope.

You can now use the token in another secret, for example `COMPOSER_AUTH` with the following shape :

```
{"github-oauth": {"github.com": "XXXXXXXXXXXXXXXXXXXXXXXX" }}
```

**Comment by htollefsen** [comment]
Alright, thanks

**Comment by miloskroulik** [comment]
> The `GITHUB_TOKEN` secret won't work in your context because is it **scoped to the current repository**. I had the same problem on my project and I had to create a personal access token.
> To generate such a personal access token, simply go to https://github.com/settings/tokens and make a token with the `repo` scope.
> 
> You can now use the token in another secret, for example `COMPOSER_AUTH` with the following shape :
> 
> ```
> {"github-oauth": {"github.com": "XXXXXXXXXXXXXXXXXXXXXXXX" }}
> ```

Unfortunately, this didn't work for me. I got this error:

```
  [UnexpectedValueException]                                                                                                                           
  Your github oauth token for github.com contains invalid characters: "***"
```

Did anyone else also experienced a problem like this?

**Comment by shivammathur** [comment]
@miloskroulik 
You can verify your token by fetching details of a private repository in your account.
```bash
curl -i -u <username>:<token> https://api.github.com/repos/<username>/<private_repository>
```
If the token is valid, you will see the repository details, otherwise you will get a 404.

Once you have verified the token, you can configure it using setup-php like this.

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.4'
  env:
    COMPOSER_TOKEN: ${{ secrets.YOUR_TOKEN }}
```

If you face any problems, please create another issue with the relevant details.

**Comment by miloskroulik** [comment]
Thanks for your help, @shivammathur. In the end, I just added my personal token to the secret - there's not need to wrap it to the JSON structure outlined above.
