### ISSUE TITLE
Examples are misleading - Need update

### ISSUE THREAD

**Issue by drupol** [shivammathur/setup-php#131]
Hello,

I'm using your Github actions in my repositories.
I followed the examples files to enable the dependencies cache to speed up my builds and it failed.

Let's take this example: https://github.com/shivammathur/setup-php/blob/master/examples/slim-framework.yml

We can see that it's trying to get the hash of the file `composer.lock` which is only there AFTER doing `composer install`.

I would update the examples accordingly and add the `composer install` step before the `Cache composer dependencies` step. For all the examples.

In case of an already existing `composer.lock` in the repository, it doesn't change a thing.

**Comment by shivammathur** [comment]
It is assuming that you have a `composer.lock` in your repository, most projects commit `composer.lock`. In case you do not do the same, use `composer.json` as key to cache dependencies.

```yml
key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
```

**Comment by shivammathur** [comment]
@drupol To give more clarity on this, the cache steps have to be before the `composer install` as the same step restores the cache and adds a steps at the end of the workflow to save the cache for future runs. Therefore you cannot use a file that is generated in the `composer install` step. So the examples are correct. I will try to make this more clear in the documentation in next release.

Let me know if you have any questions.

**Comment by drupol** [comment]
Hi,

Most of the libraries are not shipping `composer.lock`, examples:

Slim: https://github.com/slimphp/Slim
Lumen: https://github.com/laravel/lumen
Symfony: https://github.com/symfony/symfony (+ all the other components)
... 

So, the examples files are wrong because they would not work as they are for those projects.

I will do the changes you advised me and use `composer.json` file instead of `composer.lock`.

**Comment by shivammathur** [comment]
Yes, currently all the examples are written for skeleton apps of frameworks, not libraries or frameworks themselves. If you are creating a library/framework and support a range of your dependencies use can `composer.json` as cache key. 

When you are using a framework like `symfony` for creating a web store it makes sense to commit your composer.lock so that when you deploy on the server it use same dependencies and works. If you are creating a library/framework itself and decide not to commit you composer.lock as you would support a range of versions of your dependencies you can choose `composer.json`. 

Will make this more clear in the examples and documentation in the next release.

**Comment by drupol** [comment]
Thanks mate!

**Comment by shivammathur** [comment]
Updated examples and documentation in #133

**Comment by drupol** [comment]
It's perfect 🤗
