### ISSUE TITLE
Getting warning regaring pecl

### ISSUE THREAD

**Issue by ADmad** [shivammathur/setup-php#141]
Error message

```
##[warning]Input 'pecl' has been deprecated with message: The pecl property will not be supported after February 1, 2020. Specify pecl in tools instead.
```

https://github.com/cakephp/cakephp/pull/14129/checks?check_run_id=375597868#step:4:1

**Comment by ADmad** [comment]
Apologies, I can fix the error by following the error message :)

**Comment by shivammathur** [comment]
Yes, specify `pecl` in the tools input

**Comment by ADmad** [comment]
Is this config change required due to change in some external tool / service?

**Comment by shivammathur** [comment]
No, I added support for installing various tools globally via `tools` input. [Please see](https://github.com/shivammathur/setup-php#wrench-tools-support), so it made sense to refactor `pecl` installation in that instead of a separate input for it.

**Comment by ADmad** [comment]
I find it strange that you are forcing users to update their config before a deadline. Since github actions are versions wouldn't it more prudent to simply release a new major version if your script has a breaking change? That way using using `v1` wouldn't need to make any change.

**Comment by shivammathur** [comment]
The change currently is not a breaking one, it is just a warning that some inputs have been deprecated and at this point old inputs will function just like they used to. I added this warning because many projects use `master` and changing inputs suddenly without warning will be abrupt. 

The date mentioned in the warning is around the time I plan to release `v2` and remove support for old inputs in that which will be a breaking change.

**Comment by ADmad** [comment]
Okay, in that cause a message like `The 'pecl' property will be removed in v2` would have made more sense rather than specifying a date IMHO.

**Comment by shivammathur** [comment]
ok. I will make these more clear in the next release.

**Comment by ADmad** [comment]
Thank you.
