### ISSUE TITLE
Composer 2 wrong version

### ISSUE THREAD

**Issue by GrahamCampbell** [shivammathur/setup-php#238]
`composer:v2` downloads the latest dev version instead of `2.0.0alpha2`, and similar for `composer:v1`.

**Comment by shivammathur** [comment]
@GrahamCampbell This on `setup-php` is mapped to composer's self-update API which follows this https://getcomposer.org/versions

So `composer:v1` gets current stable version `10.8.0`, but `composer:v2` gets the snapshot version.
Current workaround is to use `composer:preview` to get the `alpha`.

I think this should be changed upstream that `composer self-update --2` updates to `alpha` instead of `snapshot`.
Please create an issue on composer and if they decide to keep it as it is, I will remap the API it on setup-php in next release.

**Comment by GrahamCampbell** [comment]
Ah yes, thanks!

**Comment by GrahamCampbell** [comment]
This has now been fixed on Packagist. ;)

**Comment by shivammathur** [comment]
Thanks for the update, `composer:v2` now gets the `alpha`.

**Comment by GrahamCampbell** [comment]
Yep. :)
