### ISSUE TITLE
Consistency about the tidy extension across PHP versions

### ISSUE THREAD

**Issue by j0k3r** [shivammathur/setup-php#338]
**Describe the feature**
One of my project needs the tidy extension to run. So I've checked the wiki (for the ubuntu 20.04 version) and it seems the tidy extension isn't available for all PHP versions. It's available for 5.3, 7.4, 8.0 and 8.1. Why does other version are skipped?

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
None

**Describe alternatives**
Install it manually during the PHP installation (slowest build: from 20s to 60s)

**Are you willing to submit a PR?**
If there are some guidelines on how to integrate an extension into a built-in PHP version.

**Comment by shivammathur** [comment]
It is difficult to enable an extension by default for all PHP versions as they are installed differently across OS. On Ubuntu 16.04 it is enabled by default now for all PHP versions, so you may switch to that.
Otherwise, if you specify tidy in `extensions` input, it will be installed if not present on all supported PHP versions.

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/369103705/workflow

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.4'
    extensions: tidy
```

**Comment by j0k3r** [comment]
Looks like you've updated 18.04 too, thanks!

**Comment by shivammathur** [comment]
Yes, it should be enabled on all versions except PHP 5.6 and 7.0 as they are installed on each run on Ubuntu 18.04
