### ISSUE TITLE
ini-values are only added to CLI php.ini

### ISSUE THREAD

**Issue by acasademont** [shivammathur/setup-php#352]
**Describe the bug**
In a test we need to run the php-cgi SAPI. We've seen that the `ini-values` directive is only added to the CLI ini file. Ideally, all ini-values should be added to all available SAPIs. Thank you!

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [ ] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu Lastest

**PHP versions**
All php versions

**To Reproduce**
add a "ini-values" directive, it will be added to the cli/php.ini file, but not to the cgi/php.ini file

**Expected behavior**
ini-values should be added to all sapis

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by acasademont** [comment]
In the meantime I tried to change the CGI ini file in the actions themselves but it seems I don't have permissions to do so. Any workaround would be highly appreciated :D

**Comment by shivammathur** [comment]
@acasademont I will work on this today, as it will need testing extension setup if I change how ini files are handled.

**Comment by acasademont** [comment]
@shivammathur maybe another "cgi-ini-values" property would be easier for you? Happy to help in any way I can, we're trying to move https://github.com/php-pm/php-pm repo to GH actions.

**Comment by shivammathur** [comment]
@acasademont I have added support to add ini directives mentioned in `ini-values` input to all installed SAPIs. Since `php-cgi` is installed on `ubuntu-18.04` for the php versions you are using, it should now work for your use case.
Let me know if you face any issues.

I'm adding support to install SAPIs, that will be in next release.

**Comment by shivammathur** [comment]
@acasademont I have added support to add `ini-values` to all the installed SAPIs. 

Since `php-cgi` is installed on `ubuntu-18.04` for the php versions you are using, it should work for your use case.
Let me know if you face any issues.

I'm adding support to install SAPIs, that will be in next release.

**Comment by acasademont** [comment]
@shivammathur thanks a lot! It worked like a charm :D Really appreciate it!

**Comment by aszenz** [comment]
@shivammathur Should this also work with php-fpm when used via nginx, I have an app throwing memory limit exceeded error even though I have already set the memory limit using `ini-values`
