### ISSUE TITLE
pdo_mysql isn't installed

### ISSUE THREAD

**Issue by samdark** [shivammathur/setup-php#412]
pdo_mysql is not available despite [being specified in `extensions` when using `v2` version of the action](https://github.com/yiisoft/yii/blob/master/.github/workflows/build.yml#L11).

See https://github.com/yiisoft/yii/pull/4347/checks?check_run_id=1931296014

We check the code with `extension_loaded('pdo_mysql')` https://github.com/yiisoft/yii/pull/4347/files

![image](https://user-images.githubusercontent.com/47294/108436485-92c6ec80-725c-11eb-8bc7-77e9a032e4e1.png)

![image](https://user-images.githubusercontent.com/47294/108436521-9ce8eb00-725c-11eb-97cd-1475da289368.png)

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/setup-php/commit/3f36c0511e6b5c06cdbb82f098b7a32ccf1a1203

Test workflows:
Before cache - https://github.com/shivammathur/test-setup-php/runs/1932619779?check_suite_focus=true
After cache - https://github.com/shivammathur/test-setup-php/runs/1932630635?check_suite_focus=true

Also fixed cache support for `cubrid` and `pdo_cubrid` in https://github.com/shivammathur/setup-php/commit/36ec0200a6fc212f80e2e08b7a2e2d63413ee119

**Comment by samdark** [comment]
Awesome! Thank you!

**Comment by samdark** [comment]
Under PHP 5.6 there's related issue: https://github.com/yiisoft/yii/runs/1933365142

**Comment by shivammathur** [comment]
@samdark Please try now.

**Comment by samdark** [comment]
Works. Thank you!
