### ISSUE TITLE
default extension list is different depending on PHP versions being preinstalled or no.

### ISSUE THREAD

**Issue by stof** [shivammathur/setup-php#422]
**Describe the bug**
When the selected PHP version is not pre-installed, the extensions available by default (without any `extensions` config being set) are not the same than when the version is preinstalled.
With github migrating `ubuntu-latest` from `ubuntu-18.04` to `ubuntu-20.04` which removed PHP 7.3 and older from preinstalled versions, this issue is likely to break more repositories.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
linux (maybe others too, but not tested)

**PHP versions**
7.1

**To Reproduce**

**Expected behavior**
As pdo_mysql is enabled by default in preinstalled PHP versions, it should also be enabled by default when installing another PHP version without configuring extensions IMO (same for other extensions of course)

**Screenshots/Logs**
See https://github.com/symfony/maker-bundle/pull/828 for an example

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
Installing the same extensions on `ubuntu-20.04` with PHP 7.3 as the preinstalled versions would take 1-2 minutes for everyone. Instead all the extensions which are needed should be specified so that workflow is optimised as per the requirement.

Also, You can always use `ubuntu-18.04` or `ubuntu-16.04` instead of `ubuntu-latest`.
https://github.com/shivammathur/setup-php#github-hosted-runners

But, in my opinion GitHub Actions images should provide the same PHP versions pre-installed on all ubuntu versions as `ondrej/ppa` supports PHP 5.6 and above, and provides security patches for them. So please ask [actions team](https://github.com/actions/virtual-environments) to improve this.

I think they are following Travis CI, but Travis compiled PHP using `php-build`, which does not provide any security patches and thus required dropping PHP versions as they deprecated.

**Comment by shivammathur** [comment]
@stof
Installing the same extensions on `ubuntu-20.04` with PHP 7.3 as the preinstalled versions would take 1-2 minutes for everyone. Instead all the extensions which are needed should be specified in extensions input so that workflow is optimised as per the requirement.

Another solution is using `ubuntu-18.04` or `ubuntu-16.04` instead of `ubuntu-latest`.
https://github.com/shivammathur/setup-php#github-hosted-runners

But, in my opinion GitHub Actions images should provide the same PHP versions pre-installed on all ubuntu versions as `ondrej/ppa` supports PHP 5.6 and above, and provides security patches for them. So please ask [actions team](https://github.com/actions/virtual-environments) to improve this.

I think they are following Travis CI, but Travis compiled PHP using `php-build`, which does not provide any security patches and thus required dropping PHP versions as they deprecated.

**Comment by shivammathur** [comment]
Considering `mysql` and `pdo_mysql` are widely used, They should now be installed with every PHP version on ubuntu. As for other extensions they should be specified in extensions input as required.

**Comment by shivammathur** [comment]
@stof @driesvints 
After cache improvements in https://github.com/shivammathur/php-ubuntu/commit/1693db3f0707e0d1201282dab40857cd341d6664, on all three supported ubuntu versions same set of extensions should be available by default when PHP is installed as they are when PHP is pre-installed.

**Comment by driesvints** [comment]
@shivammathur that's great, thanks! I'll roll out updates for ubuntu-20.04 soon.

**Comment by stof** [comment]
@shivammathur that's great news
