### ISSUE TITLE
Add support for a "nightly" alias

### ISSUE THREAD

**Issue by williamdes** [shivammathur/setup-php#491]
**Describe the bug**

I had to comment out the next PHP 8.2 version as it does not exist yet for this action.
See: https://github.com/phpmyadmin/sql-parser/commit/dd2f634b9918ef7986783b324c734016ef7d2f09

TravisCI (sorry to mention it, I would prefer that we forget about it) had support for "nightly" in the php version matrix. This was helpfull

**Are you willing to submit a PR?**
Sorry, I am missing time

**Comment by williamdes** [comment]
Ah, form mistake, not a bug

**Comment by shivammathur** [comment]
8.2 should work and set up `8.2.0-dev` from the master branch of php. I added builds last week. The docs will be updated in the next release.
Test workflow: https://github.com/shivammathur/setup-php/runs/3496421413?check_suite_focus=true#step:6:1

In Travis, IMHO this was broken as they won't update the nightly as it would shift to the next to next version (8.2) and you would not be testing the next version (8.1) in your workflow until support is added for it and you add it to your workflow.

Instead of a nightly tag, I would rather prefer that for testing master, projects add the version in the workflow.

**Comment by shivammathur** [comment]
Added in develop (https://github.com/shivammathur/setup-php/commit/d068c17d9e2904a5b2c36561a68ad75857c30a22). It Will be in the next release.
Test workflow; https://github.com/shivammathur/test-setup-php/actions/runs/1204939520/workflow

**Comment by williamdes** [comment]
> Added in develop ([d068c17](https://github.com/shivammathur/setup-php/commit/d068c17d9e2904a5b2c36561a68ad75857c30a22)). It Will be in the next release.
> Test workflow; https://github.com/shivammathur/test-setup-php/actions/runs/1204939520/workflow

Thank you so much!
Will wait for the release and apply this on all repos

**Comment by shivammathur** [comment]
Released in [`2.14.0`](https://github.com/shivammathur/setup-php/releases/tag/2.14.0)
