### ISSUE TITLE
Php version on ubuntu is not updated to php 8.0.15 using env: update: true

### ISSUE THREAD

**Issue by terabytesoftw** [shivammathur/setup-php#559]
**Describe the bug**
Php version on ubuntu is not updated to php 8.0.15 using env: update: true
**Version**
- [x] `v2`

**Runners**

- [x] GitHub Hosted

**Operating systems**
ubuntu.

**PHP versions**
8.0

**To Reproduce**
- name: Install PHP with extensions
  uses: shivammathur/setup-php@v2
  with:
    php-version: ${{ matrix.php }}
    extensions: ${{ env.extensions }}
    ini-values: date.timezone='UTC'
    coverage: pcov
    tools: composer:v2
  env:
    update: true

**Expected behavior**
`PHP 8.0.15` Install.

**Comment by shivammathur** [comment]
PHP 8.0 is `8.0.14` on `ppa:ondrej/php`. Once updated on the PPA I will refresh the cache we have. Please report this [here](https://github.com/oerdnj/deb.sury.org)

**Comment by shivammathur** [comment]
It should be `8.015` now.

**Comment by Stoyvo** [comment]
@shivammathur Please revert to PHP 8.0.14, or provide a way to use a patch version. PHP 8.0.15 has an issue with SplFileObjects, it's fixed in php-8.1.3RC1, php-8.1.2, php-8.1.2RC1, php-8.0.16RC1, php-8.0.15, php-8.0.15RC1:
https://github.com/php/php-src/commit/daf79e2d91dc4dd47f516229ebc5922ad35f27ab
