### ISSUE TITLE
Update the list of supported OS and PHP versions on GitHub runners

### ISSUE THREAD

**Issue by gggeek** [shivammathur/setup-php#665]
**Describe the feature**
GitHub is soon removing the possibility of using runners based on Ubuntu 18. In fact, tests using that OS version have already started failing randomly as a "warning" strategy.
I tried installing php 5.3, 5.4 and 5.5 on GitHub's Ubuntu 20 and 22, and both cases failed. I presume this is to those ancient versions having been dropped from the php repos used by the action.

I think the Readme should be updated to reflect the current supported versions status.

**Comment by shivammathur** [comment]
I will update the README once it is removed, PHP 5.3, 5.4 and 5.5 should still work on all 3 Ubuntu OS GitHub runners listed in the workflow.
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/3470290671/workflow

Please restart your workflow if it failed, sometimes that happens because it fails to fetch the build.
If it is still failing and something specific is not working please recreate the issue on a public repo and share the workflow URL.

**Comment by gggeek** [comment]
My bad - I double-checked the failed workflows and the problem was indeed in setting up phpunit, not php. Sorry for the noise
