### ISSUE TITLE
Could not install zephir_parser on PHP x.x.xx

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#681]
**Describe the bug**
It is impossible to install pecl package inside Windows env.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Windows2019

**PHP versions**
Any

**To Reproduce**
https://github.com/zephir-lang/zephir/actions/runs/3790395319/jobs/6449129559#step:3:35

**Comment by shivammathur** [comment]
@Jeckerson 
There are no DLLs for zephir_parser 1.5.2 currently, it will work once they are added to PECL. 

Suppose the extension is needed and the exact semver version is not important. In that case, you can remove the version from the input and it will install the latest available extension version with the DLL for the PHP version.
Otherwise, I can add support for the extension using GitHub releases in the next release.

**Comment by Jeckerson** [comment]
I might be incorrect, but I noticed that pecl, some time ago, stopped to release win .dll files.
And if look inside this folders https://windows.php.net/downloads/pecl/releases/ none contain recent releases.

@shivammathur Could you pick .dll from release assets? https://github.com/zephir-lang/php-zephir-parser/releases/tag/v1.5.2

**Comment by shivammathur** [comment]
Added support in https://github.com/shivammathur/setup-php/commit/7abee8e28c06b766cef0828e207a8279bc8f111e. Will be in the next release.

**Comment by shivammathur** [comment]
Released in [2.24.0](https://github.com/shivammathur/setup-php/releases/tag/2.24.0)
