### ISSUE TITLE
some PHP Versions get into endless loops

### ISSUE THREAD

**Issue by Flyingmana** [shivammathur/setup-php#83]
**Describe the bug**
PHP is seemingly running into endless loops in certain versions.
Actually, only the Version 5.6 seems to work properly for this case.

**To Reproduce**
You can find the .yml file inside as part of this PR https://github.com/OpenMage/magento-lts/pull/853/checks?check_run_id=317380325

**Expected behavior**
To have the php command running through as it does in travis.ci
see https://travis-ci.org/OpenMage/magento-lts/jobs/615974331

**Screenshots**
screenshot from this job run: https://github.com/OpenMage/magento-lts/runs/302616678
![image](https://user-images.githubusercontent.com/237319/69480287-84dead80-0e06-11ea-8d8c-477b83291e76.png)

**Additional context**
There may be a chance, that the Issue is with Github Actions in general, and not with the setup-php action, but Iam running out of ideas to validate or detect the actual Issue.

I tried out several combinations to group them in separate jobs in different orders.

**Comment by shivammathur** [comment]
@Flyingmana 
The issue is not with PHP or with this GitHub action. Change your file descriptor to `>/dev/null` instead of `2>&1 >&-` and it should run correctly.
I tested with `>/dev/null` and it worked, see [test yml](https://github.com/shivammathur/magento-lts/blob/master/.github/workflows/static-code-analyses.yml) and [test workflow](https://github.com/shivammathur/magento-lts/commit/f7fef96dfa719411e195a204c78e0fda60924b3c/checks?check_suite_id=325654553)

**Comment by Flyingmana** [comment]
thank you very much, this really helped.
Iam not exactly sure, why it did still work for one of the cases, but I now understand what did cause the issue.
